version: 2.1

orbs:
  ci-go: ipfs/ci-go@0.2

executors:
  go-postgres:
    docker:
      - image: circleci/golang:1.13.8
      - image: circleci/postgres:latest
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust

workflows:
  version: 2
  test:
    jobs:
    - ci-go/build
    - ci-go/lint
    - ci-go/test:
        executor: go-postgres
