version: 2.1

orbs:
  ci-go: ipfs/ci-go@0.2

executors:
  go-s3:
    docker:
      - image: circleci/golang:1.13.7
      - image: postgres
    environment:
      LOCAL_S3: 1
      SERVICES: s3

workflows:
  version: 2
  test:
    jobs:
    - ci-go/build
    - ci-go/lint
    - ci-go/test:
        executor: go-s3
